### PR TITLE
Enable Deno workspace

### PR DESCRIPTION
**Pull request by quadratz**

### CODE REVIEW

**Comment by rojvv** [comment]
Isn’t Deno globally enabled for you?

**Review by KnorpelSenf — APPROVED** [review]
It isn't for me, as I try to use as little global config as humanly possible

**Comment by rojvv** [comment]
Then just ignore `/.vscode` globally?

**Comment by KnorpelSenf** [comment]
What do you mean?

**Comment by rojvv** [comment]
```shell
echo "/.vscode" > ~/.gitignore
```

**Comment by KnorpelSenf** [comment]
How does this help me keep config local?

**Comment by rojvv** [comment]
You just recreate that local config every time you contribute to translations-bot which you won’t.

**Comment by KnorpelSenf** [comment]
Do you think that's a better setup than the one suggested by this pull request? If the goal is that anyone can clone this repo and the setup will just work, then we should recommend the Deno extension and have local config. Am I missing something?

**Pull request merged**
